all:
	g++ -Ofast main.cpp -I/usr/include/pcl-1.8 -fopenmp -I/usr/include/eigen3 -I /usr/include/vtk-6.3 -lpcl_io_ply -lboost_system -lpcl_io -lpcl_common -lpcl_visualization -lvtkCommonDataModel-6.3 -lvtkCommonCore-6.3 -lvtkRenderingCore-6.3 -lvtkCommonMath-6.3 -lpcl_registration -lpcl_search -lpcl_filters -Wno-deprecated-declarations -o rotate
